version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: carrent
      MYSQL_DATABASE: carrentapp
    ports:
      - "3306:3306"

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mysql
