# Use the official Node.js image as base
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server application code to the working directory
COPY . .

# Expose port 5000
EXPOSE 5000

# Command to run the server
CMD ["node", "index.js"]
